### PR TITLE
add types field to exports

### PR DESCRIPTION
**Pull request by o-az**
https://publint.dev/rules#types_not_exported

https://publint.dev/@shadeprotocol/shadejs@1.0.2

### CODE REVIEW

**Comment by AustinWoetzel** [comment]
thanks for the PR, please include a changeset which helps us with version control.  You can do this by running 
`yarn changeset`

**Comment by AustinWoetzel** [comment]
Please change the base to the 'develop' branch rather than main.

**Review by AustinWoetzel — CHANGES_REQUESTED** [review]
Thanks for this PR! See comments for a couple procedural changes.

**Comment by AustinWoetzel** [comment]
By the way, I think our docs need some improvements so that these procedural requirements are more clear.

**Comment by cmartinho** [comment]
Please use `yarn commitizen` for the commit structure

**Review by AustinWoetzel — APPROVED** [review]

**Pull request merged**
